resources:
  - name: A_6805_0001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
      branches:
        include: main


pipelines:
  - name: testReports
    steps:
      - name: step_with_tests
        type: Bash
        configuration:
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_1.xml"
      - name: no_tests_here
        type: Bash
        configuration:
          inputSteps:
            - name: step_with_tests
        execution:
          onExecute:
            - sleep 1
            - echo "done"
