resources:
  - name: A_6805_0001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
      branches:
        include: main


pipelines:
  - name: testReports
    steps:
      - name: step_with_tests_1
        type: Bash
        configuration:
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_1.xml"
      - name: no_tests_here
        type: Bash
        configuration:
          inputSteps:
            - name: step_with_tests_1
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: step_with_tests_2
        type: Bash
        configuration:
          inputSteps:
            - name: no_tests_here
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_2.xml"
      
      - name: matrix_step
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - steplet: 1
              file: v3_example_1.xml
            - steplet: 2
              file: v3_example_2.xml
        configuration:
          inputSteps:
            - name: step_with_tests_2
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - echo "Variation steplet = ${steplet}, file = ${file}"
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/${file}"
