resources:
  - name: A_6805_0001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
      branches:
        include: main


pipelines:
  - name: A_6805_0001
    steps:
      - name: A_6805_0001_1
        type: Bash
        configuration:
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_1.xml"
