
resources:
  - name: propertyCanvas10a
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: buildInfoTrigger10a
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtIntegration
      buildName: backend_build
      buildNumber: 1
pipelines:
  - name: canvasTest10a
    steps:
      - name: canvasTest_Root10a
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_1_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_2_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_3_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_4_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_5_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_6_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_7_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_8_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_9_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_10_1
        type: Bash
        configuration:
          inputSteps:
            - name: canvasTest_Root10a
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      