resources:
  - name: inp1
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
pipelines:
  - name: rrrrreeeeeaaaaalllllyyyyylooooonnnnngnameeeee
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: inp1
        execution:
          onExecute:
            - sleep 10
            - echo "done"
