
resources:
  - name: propertyCanvas10b
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: buildInfoTrigger10b
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtIntegration
      buildName: backend_build
      buildNumber: 1
pipelines:
  - name: canvasTest10b
    configuration:
      environmentVariables:
        readOnly:
          pipeLevel1: pipeValue1
          pipeLevel2: pipeValue2
    steps:
      - name: canvasTest_Root10
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_1_1
        type: Bash
        configuration:
          environmentVariables:
            stepLevel1: stepValue1
            stepLevel2: stepValue2
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_2_1
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_3_1
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_4_1
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_5_1
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_6_1
        type: Bash
        configuration:
          affinityGroup: groupa
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_7_1
        type: Bash
        configuration:
          affinityGroup: groupb
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_8_1
        type: Bash
        configuration:
          affinityGroup: groupa
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_9_1
        type: Bash
        configuration:
          affinityGroup: groupb
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: canvasTest10_1_10_1
        type: Bash
        configuration:
          inputResources:
            - name: propertyCanvas10b
            - name: buildInfoTrigger10b
          inputSteps:
            - name: canvasTest_Root10
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      
