resources:
  - name: A_6805_0001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
      branches:
        include: main


pipelines:
  - name: testReports
    steps:
      - name: step_with_tests_1
        type: Bash
        configuration:
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_1.xml"
      - name: no_tests_here
        type: Bash
        configuration:
          inputSteps:
            - name: step_with_tests_1
        execution:
          onExecute:
            - sleep 1
            - echo "done"
      - name: step_with_tests_2
        type: Bash
        configuration:
          inputSteps:
            - name: no_tests_here
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_2.xml"
      - name: step_with_tests_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_with_tests_2
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/tr21.xml"
      - name: matrix_step
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - steplet: 1
              file_name: v3_example_1.xml
            - steplet: 2
              file_name: v3_example_2.xml
        configuration:
          inputSteps:
            - name: step_with_tests_3
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - echo "Variation steplet ${steplet}, fileName ${file_name}"
            - | 
              if [[ $steplet -eq 1 ]]; then
                save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_1.xml"
              else
                save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/v3_example_2.xml"
              fi
      - name: TestElement_3
        type: Bash
        configuration:
          inputSteps:
            - name: matrix_step
          inputResources:
            - name: A_6805_0001_GitRepo
        execution:
          onExecute:
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/test-result.4e487d4f4e582e7f0674f1d643b7c189.xml"
            - save_tests "$res_A_6805_0001_GitRepo_resourcePath/tests/junit/test-result.9bf1a1b430b262590fc69b1c9e2f1ae1.xml"
